export const Department = {
  GENERAL_MEDICINE: "General Medicine",
  FAMILY_MEDICINE: "Family Medicine",
  CARDIOLOGY: "Cardiology",
  DERMATOLOGY: "Dermatology",
  PEDIATRICS: "Pediatrics",
  ORTHOPEDICS: "Orthopedics",
  NEUROLOGY: "Neurology",
  PSYCHIATRY: "Psychiatry",
  PSYCHOLOGY: "Psychology",
  GYNECOLOGY: "Gynecology",
  OBSTETRICS: "Obstetrics",
  OPHTHALMOLOGY: "Ophthalmology",
  ENT: "ENT",
  DENTISTRY: "Dentistry",
  UROLOGY: "Urology",
  NEPHROLOGY: "Nephrology",
  GASTROENTEROLOGY: "Gastroenterology",
  PULMONOLOGY: "Pulmonology",
  ENDOCRINOLOGY: "Endocrinology",
  RHEUMATOLOGY: "Rheumatology",
  ONCOLOGY: "Oncology",
  HEMATOLOGY: "Hematology",
  INFECTIOUS_DISEASE: "Infectious Disease",
  PHYSIOTHERAPY: "Physiotherapy",
  NUTRITION_AND_DIETETICS: "Nutrition and Dietetics",
} as const;