export const TYPES = {
  DoctorRepo: Symbol.for("DoctorRepo"),
  DoctorRequestRepository: Symbol.for("DoctorRequestRepository"),
  S3FileUploadService: Symbol.for("S3FileUploadService"),
  S3FileAccessService: Symbol.for("S3FileAccessService"),
  GetSignedFileUrlUseCase: Symbol.for("GetSignedFileUrlUseCase"),
  GetFileURlController: Symbol.for("GetFileURlController"),
  GetAllDoctorRequestUseCase: Symbol.for("GetAllDoctorRequestUseCase"),
  GetDoctorRequestUseCase: Symbol.for("GetDoctorRequestUseCase"),
  DoctorRequestUsecase: Symbol.for("DoctorRequestUsecase"),
  DoctorRequestFileService: Symbol.for("DoctorRequestFileService"),
  DoctorVerificationTokenRepository: Symbol.for(
    "DoctorVerificationTokenRepository",
  ),
  EmailService: Symbol.for("EmailService"),
  ApproveDoctorRequestUsecase: Symbol.for("ApproveDoctorRequestUsecase"),
  VerifyDoctorSetupTokenUseCase: Symbol.for("VerifyDoctorSetupTokenUseCase"),
  DoctorRetryTokenRepository: Symbol.for("DoctorRetryTokenRepository"),
  GetDoctorRetryRequest: Symbol.for("GetDoctorRetryRequest"),
  RejectdoctorRequestUseCase: Symbol.for("RejectdoctorRequestUseCase"),
  RetryDoctorRequestUseCase: Symbol.for("RetryDoctorRequestUseCase"),
  HashService: Symbol.for("HashService"),
  SetPasswordUsecase: Symbol.for("SetPasswordUsecase"),
  CreateDepeartmentUseCase: Symbol.for("CreateDepeartmentUseCase"),
  GetDepartmentUsecase: Symbol.for("GetDepartmentUsecase"),
  UpdateDepartmentUseCase: Symbol.for("UpdateDepartmentUseCase"),
  DeleteDepartmentUseCase: Symbol.for("DeleteDepartmentUseCase"),
  RestoreDepaertment: Symbol.for("RestoreDepaertment"),
  AdminRepo: Symbol.for("AdminRepo"),
  AdminUseCase: Symbol.for("AdminUseCase"),
  RefreshAdminUseCase: Symbol.for("RefreshAdminUseCase"),
  LogoutUseCase: Symbol.for("LogoutUseCase"),
  JWTService: Symbol.for("JWTService"),
  DoctorLoginUseCase: Symbol.for("DoctorLoginUseCase"),
  RefreshDoctorUseCase: Symbol.for("RefreshDoctorUseCase"),
  LogoutDoctorUseCase: Symbol.for("LogoutDoctorUseCase"),
  RequestDoctorForgetPasswordUseCase: Symbol.for(
    "RequestDoctorForgetPasswordUseCase",
  ),
  DoctorResetTokenRepo: Symbol.for("DoctorResetTokenRepo"),
  ResetDoctorPassowrd: Symbol.for("ResetDoctorPassowrd"),
  PatientRepo: Symbol.for("PatientRepo"),
  PatientOTPRepo: Symbol.for("PatientOTPRepo"),
  CounterRepo: Symbol.for("CounterRepo"),
  CreatePatientUSeCase: Symbol.for("CreatePatientUSeCase"),
  VerifyPatientOTPUsecase: Symbol.for("VerifyPatientOTPUsecase"),
  ResentOTPUsecase: Symbol.for("ResentOTPUsecase"),
  LoginPatientUseCase: Symbol.for("LoginPatientUseCase"),
  LogoutPatientUseCase: Symbol.for("LogoutPatientUseCase"),
  RefreshPatientToken: Symbol.for("RefreshPatientToken"),
  PatientrResetTokenRepo: Symbol.for("PatientrResetTokenRepo"),
  RequestPatientForgetPasswordUseCase: Symbol.for(
    "RequestPatientForgetPasswordUseCase",
  ),
  ResetPatientPassowrd: Symbol.for("ResetPatientPassowrd"),
  GetAllDoctorsUSeCase: Symbol.for("GetAllDoctorsUSeCase"),
  ToggelDoctorStatus: Symbol.for("ToggelDoctorStatus"),
  GetAllPatientUseCase: Symbol.for("GetAllPatientUseCase"),
  TogglePatientUsecase: Symbol.for("TogglePatientUsecase"),
  DoctorAvailabilityRepo: Symbol.for("DoctorAvailabilityRepo"),
  CreateDoctorAvailUseCase: Symbol.for("CreateDoctorAvailUseCase"),
  UpdateDoctorAvailabilityUseCase: Symbol.for(
    "UpdateDoctorAvailabilityUseCase",
  ),
  DeleteDoctorAvailUsecase: Symbol.for("DeleteDoctorAvailUsecase"),
  GetDoctorAvailUsecase: Symbol.for("GetDoctorAvailUsecase"),
  DoctorLeaveRepo: Symbol.for("DoctorLeaveRepo"),
  CreateDoctorLeave: Symbol.for("CreateDoctorLeave"),
  UpdateDoctorLeave: Symbol.for("UpdateDoctorLeave"),
  DeleteDoctorLeaveusecase: Symbol.for(" DeleteDoctorLeaveusecase"),
  GetAllDoctorLeaveUsecase: Symbol.for("GetAllDoctorLeaveUsecase"),
  DoctorBlockRepo: Symbol.for("DoctorBlockRepo"),
  CreateDoctorBlockUseCase: Symbol.for("CreateDoctorBlockUseCase"),
  UpdateDoctorBlockUsecase: Symbol.for("UpdateDoctorBlockUsecase"),
  DeleteDoctorBlockUsecase: Symbol.for("DeleteDoctorBlockUsecase"),
  GetDoctorBlockUsecase: Symbol.for("GetDoctorBlockUsecase"),
  GetDatesForAppointment: Symbol.for("GetDatesForAppointment"),
  AppointmentController: Symbol.for("AppointmentController"),
  GetTimeSlotUseCase: Symbol.for("GetTimeSlotUseCase"),
  AppoitmentRepo: Symbol.for("AppoitmentRepo"),
  CreateAppointmentUsecase: Symbol.for("CreateAppointmentUsecase"),
  GetAppointmentDetailsUseCase: Symbol.for("GetAppointmentDetailsUseCase"),
  GetAppointmentHistory: Symbol.for("GetAppointmentHistory"),
  GetAppointmentDoctorHistory: Symbol.for("GetAppointmentDoctorHistory"),
  AppointmentDeatilsPage: Symbol.for("AppointmentDeatilsPage"),
  AppointmentCancel: Symbol.for("AppointmentCancel"),
  AppointmentReschedule: Symbol.for("AppointmentReschedule"),
  SingleAppointmenytDetails: Symbol.for("SingleAppointmenytDetails"),
  AppointmentDoctorReschedule: Symbol.for("AppointmentDoctorReschedule"),
  DoctorGetRescheduleDetailsUseCase: Symbol.for(
    "DoctorGetRescheduleDetailsUseCase",
  ),
  AdminController: Symbol.for("AdminController"),
  DoctorController: Symbol.for("DoctorController"),
  DoctorRequestController: Symbol.for("DoctorRequestController"),
  PatientController: Symbol.for("PatientController"),
  ReviewRepo: Symbol.for("ReviewRepo"),
  UpdateReview: Symbol.for("UpdateReview"),
  CreateReview : Symbol.for("CreateReview"),
  DeleteReview : Symbol.for("DeleteReview"),
  GetReviews : Symbol.for("GetReviews")
   
};
