export const TYPES = {
  DoctorRepo: Symbol.for("DoctorRepo"),
  DoctorRequestRepository: Symbol.for("DoctorRequestRepository"),
  S3FileUploadService: Symbol.for("S3FileUploadService"),
  S3FileAccessService: Symbol.for("S3FileAccessService"),
  GetSignedFileUrlUseCase: Symbol.for("GetSignedFileUrlUseCase"),
  GetFileURlController: Symbol.for("GetFileURlController"),
  GetAllDoctorRequestUseCase: Symbol.for("GetAllDoctorRequestUseCase"),
  GetDoctorRequestUseCase: Symbol.for("GetDoctorRequestUseCase"),
  DoctorRequestUsecase: Symbol.for("DoctorRequestUsecase"),
  DoctorRequestController: Symbol.for("DoctorRequestController"),
  DoctorRequestFileService: Symbol.for("DoctorRequestFileService"),
  DoctorVerificationTokenRepository: Symbol.for(
    "DoctorVerificationTokenRepository",
  ),
  EmailService: Symbol.for("EmailService"),
  ApproveDoctorRequestUsecase: Symbol.for("ApproveDoctorRequestUsecase"),
  ApproveDoctorRequestController: Symbol.for("ApproveDoctorRequestController"),
  VerifyDoctorSetupTokenUseCase: Symbol.for("VerifyDoctorSetupTokenUseCase"),
  VerifyDoctorSetupTokenController: Symbol.for(
    "VerifyDoctorSetupTokenController",
  ),
  DoctorRetryTokenRepository: Symbol.for("DoctorRetryTokenRepository"),
  GetDoctorRetryRequest: Symbol.for("GetDoctorRetryRequest"),
  GetRetryDoctorRequestController: Symbol.for(
    "GetRetryDoctorRequestController",
  ),
  RejectdoctorRequestUseCase: Symbol.for("RejectdoctorRequestUseCase"),
  RejectDoctorRequestController: Symbol.for("RejectDoctorRequestController"),
  RetryDoctorRequestUseCase: Symbol.for("RetryDoctorRequestUseCase"),
  RetryDoctorRequestController: Symbol.for("RetryDoctorRequestController"),
  HashService: Symbol.for("HashService"),
  SetPasswordUsecase: Symbol.for("SetPasswordUsecase"),
  SetDoctorPasswordController: Symbol.for("SetDoctorPasswordController"),
  CreateDepeartmentUseCase: Symbol.for("CreateDepeartmentUseCase"),
  GetDepartmentUsecase: Symbol.for("GetDepartmentUsecase"),
  UpdateDepartmentUseCase: Symbol.for("UpdateDepartmentUseCase"),
  DeleteDepartmentUseCase: Symbol.for("DeleteDepartmentUseCase"),
  RestoreDepaertment: Symbol.for("RestoreDepaertment"),
  AdminRepo: Symbol.for("AdminRepo"),
  AdminUseCase: Symbol.for("AdminUseCase"),
  RefreshAdminUseCase: Symbol.for("RefreshAdminUseCase"),
  LogoutUseCase: Symbol.for("LogoutUseCase"),
  AdminController: Symbol.for("AdminController"),
  JWTService: Symbol.for("JWTService"),
  DoctorLoginUseCase: Symbol.for("DoctorLoginUseCase"),
  LoginDoctorController: Symbol.for("LoginDoctorController"),
  RefreshDoctorUseCase: Symbol.for("RefreshDoctorUseCase"),
  DoctorRefreshTokenController: Symbol.for("DoctorRefreshTokenController"),
  LogoutDoctorUseCase: Symbol.for("LogoutDoctorUseCase"),
  DoctorLogoutController: Symbol.for("DoctorLogoutController"),
  RequestDoctorForgetPasswordUseCase: Symbol.for(
    "RequestDoctorForgetPasswordUseCase",
  ),
  DoctorResetTokenRepo: Symbol.for("DoctorResetTokenRepo"),
  RequestResetPasswordController: Symbol.for("RequestResetPasswordController"),
  ResetDoctorPassowrd: Symbol.for("ResetDoctorPassowrd"),
  ResetDoctorPasswordController: Symbol.for("ResetDoctorPasswordController"),
  PatientRepo: Symbol.for("PatientRepo"),
  PatientOTPRepo: Symbol.for("PatientOTPRepo"),
  CounterRepo: Symbol.for("CounterRepo"),
  CreatePatientUSeCase: Symbol.for("CreatePatientUSeCase"),
  CreatePatientController: Symbol.for("CreatePatientController"),
  VerifyPatientOTPUsecase: Symbol.for("VerifyPatientOTPUsecase"),
  VerifyPatientOTP: Symbol.for("VerifyPatientOTP"),
  ResentOTPUsecase: Symbol.for("ResentOTPUsecase"),
  ResendOTPController: Symbol.for("ResendOTPController"),
  LoginPatientUseCase: Symbol.for("LoginPatientUseCase"),
  LoginPatientController: Symbol.for("LoginPatientController"),
  LogoutPatientUseCase: Symbol.for("LogoutPatientUseCase"),
  PatientLogoutController: Symbol.for("PatientLogoutController"),
  RefreshPatientToken: Symbol.for("RefreshPatientToken"),
  RefreshPatientTokenController: Symbol.for("RefreshPatientTokenController"),
  PatientrResetTokenRepo: Symbol.for("PatientrResetTokenRepo"),
  RequestPatientForgetPasswordUseCase: Symbol.for(
    "RequestPatientForgetPasswordUseCase",
  ),
  ResetPatientPassowrd: Symbol.for("ResetPatientPassowrd"),
  RequestPatientResetPasswordController: Symbol.for(
    "RequestPatientResetPasswordController",
  ),
  ResetPatientPasswordController: Symbol.for("ResetPatientPasswordController"),
  GetAllDoctorsUSeCase: Symbol.for("GetAllDoctorsUSeCase"),
  DoctorController: Symbol.for("DoctorController"),
  ToggelDoctorStatus: Symbol.for("ToggelDoctorStatus"),
  GetAllPatientUseCase: Symbol.for("GetAllPatientUseCase"),
  PatientController: Symbol.for("PatientController"),
  TogglePatientUsecase: Symbol.for("TogglePatientUsecase"),
  DoctorAvailabilityRepo: Symbol.for("DoctorAvailabilityRepo"),
  CreateDoctorAvailUseCase: Symbol.for("CreateDoctorAvailUseCase"),
  DoctorAvailController: Symbol.for("DoctorAvailController"),
  UpdateDoctorAvailabilityUseCase: Symbol.for(
    "UpdateDoctorAvailabilityUseCase",
  ),
  DeleteDoctorAvailUsecase: Symbol.for("DeleteDoctorAvailUsecase"),
  GetDoctorAvailUsecase: Symbol.for("GetDoctorAvailUsecase"),
  DoctorLeaveRepo: Symbol.for("DoctorLeaveRepo"),
  CreateDoctorLeave: Symbol.for("CreateDoctorLeave"),
  UpdateDoctorLeave: Symbol.for("UpdateDoctorLeave"),
  DeleteDoctorLeaveusecase: Symbol.for(" DeleteDoctorLeaveusecase"),
  GetAllDoctorLeaveUsecase: Symbol.for("GetAllDoctorLeaveUsecase"),
  DoctorLeaveController: Symbol.for("DoctorLeaveController"),
  DoctorBlockRepo: Symbol.for("DoctorBlockRepo"),
  CreateDoctorBlockUseCase: Symbol.for("CreateDoctorBlockUseCase"),
  UpdateDoctorBlockUsecase: Symbol.for("UpdateDoctorBlockUsecase"),
  DeleteDoctorBlockUsecase: Symbol.for("DeleteDoctorBlockUsecase"),
  GetDoctorBlockUsecase : Symbol.for("GetDoctorBlockUsecase"),
  DoctorBlockController : Symbol.for("DoctorBlockController"),
  GetDoctorsController : Symbol.for("GetDoctorsController"),
  GetDatesForAppointment : Symbol.for("GetDatesForAppointment"),
  AppointmentController : Symbol.for("AppointmentController"),
  GetTimeSlotUseCase : Symbol.for("GetTimeSlotUseCase"),
  AppoitmentRepo : Symbol.for("AppoitmentRepo"),
  CreateAppointmentUsecase : Symbol.for("CreateAppointmentUsecase"),
  GetAppointmentDetailsUseCase : Symbol.for("GetAppointmentDetailsUseCase"),
  GetAppointmentHistory : Symbol.for("GetAppointmentHistory"),
  GetAppointmentDoctorHistory : Symbol.for("GetAppointmentDoctorHistory"),
  DoctorAppointmentCOntroller : Symbol.for("DoctorAppointmentCOntroller")
};
